---
- name: Configure HAProxy
  hosts: proxy
  become: true

  vars_files:
    - vars/haproxy_vars.yml

  pre_tasks:
    - name: Open HTTP firewall port
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

  roles:
    - geerlingguy.haproxy
